# Generated by Django 3.1.5 on 2021-01-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserProfiles',
        ),
    ]
