# Generated by Django 3.1.5 on 2021-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210113_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_id',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
